# Config file for automatic testing at travis-ci.org

language: python

python:
  #- "3.4"
  - "2.7"
  #- "pypy"
  #- "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install -r requirements.txt
 - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source devp2p setup.py test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: ethereum_pypi_automated
  password:
    secure: "CoLY2r4vgY1kvJdd824hpEjmkxzs9uf2lapQNUaGB3sRytOLRAF3cfA924WFeKwp1ZVsXwKEp0ZvoLQ26JB2JqThrP7vjR24tSSN+tTkBL9h4eoHCA+W3CX+FFFHMxL6t9VCYjXHQvk/cm3zubVx/e4x1pi4WFlJCYgXY5nnStI="
  on:
    tags: true
    repo: ethereum/pydevp2p
    branch: develop
  distributions: "sdist bdist_wheel"
